node {
   def commit_id
   stage('step a') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       dir("basics"){
       sh 'npm install --only=dev'
       sh 'npm test'
       }
     }
   }
   stage('docker build/push') {
     dir("basics"){
       docker.withRegistry('https://index.docker.io/v1/', 'c5c3af58-5a12-40a9-bb06-4b7d99655c03') {
         def app = docker.build("asifeng/docker-nodejs-demo:${commit_id}", '.').push()
          
       }
       sh 'pwd'
     }
   }
   stage('docker run') {
     sh label: '', script: """docker rm docker_test || true
      docker run --rm -tid  --name docker_test -p 3000 AsifEng/docker-nodejs-demo:${commit_id}
      docker kill docker_test
      
      """
     }
   }

